# Use the official lightweight Python image.
FROM python:3.11-slim

# Update and install git
RUN apt-get update && \
    apt-get install -y gcc libffi-dev python3-dev git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory in the container.
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install jupyter
# Copy the requirements.txt and install dependencies.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
